name: structure_abstraction
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - opencv-python
    - tqdm
    - numpy
    - git+https://github.com/lettlini/core-data-utils
    - git+https://github.com/lhillma/Cell2Image.git
    - toml
